In [16]:
import seaborn as sns  #initialize in short format

sns.get_dataset_names()    #getting data


['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'taxis',
 'tips',
 'titanic']

In [17]:
df=sns.load_dataset('iris')   #loading data
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [18]:
import pandas as pd #initialize in short format

In [19]:
df #dataframe

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [20]:
df.head()   #shows top 5 rows

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [21]:
df.head(2) #shows top 2 rows

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [22]:
df.shape #tells rows & column size

(150, 5)

In [23]:
df.tail() #shows bottom 5 rows

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [24]:
df.sample() #shows random roes

sepal_length  sepal_width  petal_length  petal_width    species
105           7.6          3.0           6.6          2.1  virginica

In [25]:
df.columns #shows column names

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [26]:
df.dtypes #shows data types 

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [27]:
df.describe() #shows statistics

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [28]:
df.info() #information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [29]:
df.isna() #asking is it null if present 1 than false or true 

sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

In [30]:
df.isna().sum() #add all values

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [31]:
df.min() #mean

sepal_length       4.3
sepal_width        2.0
petal_length       1.0
petal_width        0.1
species         setosa
dtype: object

In [32]:
df.median() #middle value

C:\Users\asus\AppData\Local\Temp/ipykernel_3960/3815470365.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.median() #middle value


sepal_length    5.80
sepal_width     3.00
petal_length    4.35
petal_width     1.30
dtype: float64

In [33]:
df.var() #varience

C:\Users\asus\AppData\Local\Temp/ipykernel_3960/467282828.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.var() #varience


sepal_length    0.685694
sepal_width     0.189979
petal_length    3.116278
petal_width     0.581006
dtype: float64

In [34]:
df.std() #standard deviation

C:\Users\asus\AppData\Local\Temp/ipykernel_3960/3653657089.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.std() #standard deviation


sepal_length    0.828066
sepal_width     0.435866
petal_length    1.765298
petal_width     0.762238
dtype: float64

In [35]:
df.quantile([0.10,0.20]) # 10% and 20% 

sepal_length  sepal_width  petal_length  petal_width
0.1           4.8          2.5           1.4          0.2
0.2           5.0          2.7           1.5          0.2

In [36]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [37]:
df.petal_length.value_counts() #counts the value of petal length 

1.4    13
1.5    13
5.1     8
4.5     8
1.6     7
1.3     7
5.6     6
4.7     5
4.9     5
4.0     5
4.2     4
5.0     4
4.4     4
4.8     4
1.7     4
3.9     3
4.6     3
5.7     3
4.1     3
5.5     3
6.1     3
5.8     3
3.3     2
5.4     2
6.7     2
5.3     2
5.9     2
6.0     2
1.2     2
4.3     2
1.9     2
3.5     2
5.2     2
3.0     1
1.1     1
3.7     1
3.8     1
6.6     1
6.3     1
1.0     1
6.9     1
3.6     1
6.4     1
Name: petal_length, dtype: int64

In [38]:
df.sepal_length.value_counts()  #counts the value of sepal length 

5.0    10
5.1     9
6.3     9
5.7     8
6.7     8
5.8     7
5.5     7
6.4     7
4.9     6
5.4     6
6.1     6
6.0     6
5.6     6
4.8     5
6.5     5
6.2     4
7.7     4
6.9     4
4.6     4
5.2     4
5.9     3
4.4     3
7.2     3
6.8     3
6.6     2
4.7     2
7.6     1
7.4     1
7.3     1
7.0     1
7.1     1
5.3     1
4.3     1
4.5     1
7.9     1
Name: sepal_length, dtype: int64

# how to select specific columns in data

In [ ]:
# selecting only one column
df["mpg"] #informal way
df.mpg
df[["mpg"]] #standard way

# selecting multiple columns

df[["mpg","hp"]]

In [40]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [41]:
df[['sepal_length']]  #shows defined column

sepal_length
0             5.1
1             4.9
2             4.7
3             4.6
4             5.0
..            ...
145           6.7
146           6.3
147           6.5
148           6.2
149           5.9

[150 rows x 1 columns]

In [42]:
df[["sepal_length","petal_width"]]

sepal_length  petal_width
0             5.1          0.2
1             4.9          0.2
2             4.7          0.2
3             4.6          0.2
4             5.0          0.2
..            ...          ...
145           6.7          2.3
146           6.3          1.9
147           6.5          2.0
148           6.2          2.3
149           5.9          1.8

[150 rows x 2 columns]

# loc and iloc    loc=location & iloc=index location

In [ ]:
#df.loc
#df.iloc

df.loc[[0,1,2],["mpg","cyl","disp","hp"]]

df.iloc[0:3,0:4]


In [43]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [44]:
df.loc[[0,1,],['sepal_length','petal_width']]

sepal_length  petal_width
0           5.1          0.2
1           4.9          0.2

In [45]:
df.iloc[0:3,0:4]

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2

In [46]:
#difference b/w loc & iloc

In [47]:
df.iloc[0:3,0:4] #0:3 shows 0_2

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2

In [48]:
df.loc[0:3,:]  #0:3 shows 0_3 only drawback in python

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa

# filters


In [49]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [50]:
df['sepal_width']==3 #shows as true whose sepal width value is 3

0      False
1       True
2      False
3      False
4      False
       ...  
145     True
146    False
147     True
148    False
149     True
Name: sepal_width, Length: 150, dtype: bool

In [51]:
df[df['sepal_width']==3]  #shows the sepal width whose value is 3

sepal_length  sepal_width  petal_length  petal_width     species
1             4.9          3.0           1.4          0.2      setosa
12            4.8          3.0           1.4          0.1      setosa
13            4.3          3.0           1.1          0.1      setosa
25            5.0          3.0           1.6          0.2      setosa
38            4.4          3.0           1.3          0.2      setosa
45            4.8          3.0           1.4          0.3      setosa
61            5.9          3.0           4.2          1.5  versicolor
66            5.6          3.0           4.5          1.5  versicolor
75            6.6          3.0           4.4          1.4  versicolor
77            6.7          3.0           5.0          1.7  versicolor
84            5.4          3.0           4.5          1.5  versicolor
88            5.6          3.0           4.1          1.3  versicolor
91            6.1          3.0           4.6          1.4  versicolor
95            5.7          3.0           4.2          1.2  versicolor
102           7.1          3.0           5.9          2.1   virginica
104           6.5          3.0           5.8          2.2   virginica
105           7.6          3.0           6.6          2.1   virginica
112           6.8          3.0           5.5          2.1   virginica
116           6.5          3.0           5.5          1.8   virginica
127           6.1          3.0           4.9          1.8   virginica
129           7.2          3.0           5.8          1.6   virginica
135           7.7          3.0           6.1          2.3   virginica
138           6.0          3.0           4.8          1.8   virginica
145           6.7          3.0           5.2          2.3   virginica
147           6.5          3.0           5.2          2.0   virginica
149           5.9          3.0           5.1          1.8   virginica

In [52]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [53]:
df[(df['sepal_length']>5) & (df['sepal_width']==3)]  #& means all condition should be satisfy

sepal_length  sepal_width  petal_length  petal_width     species
61            5.9          3.0           4.2          1.5  versicolor
66            5.6          3.0           4.5          1.5  versicolor
75            6.6          3.0           4.4          1.4  versicolor
77            6.7          3.0           5.0          1.7  versicolor
84            5.4          3.0           4.5          1.5  versicolor
88            5.6          3.0           4.1          1.3  versicolor
91            6.1          3.0           4.6          1.4  versicolor
95            5.7          3.0           4.2          1.2  versicolor
102           7.1          3.0           5.9          2.1   virginica
104           6.5          3.0           5.8          2.2   virginica
105           7.6          3.0           6.6          2.1   virginica
112           6.8          3.0           5.5          2.1   virginica
116           6.5          3.0           5.5          1.8   virginica
127           6.1          3.0           4.9          1.8   virginica
129           7.2          3.0           5.8          1.6   virginica
135           7.7          3.0           6.1          2.3   virginica
138           6.0          3.0           4.8          1.8   virginica
145           6.7          3.0           5.2          2.3   virginica
147           6.5          3.0           5.2          2.0   virginica
149           5.9          3.0           5.1          1.8   virginica

In [54]:
df[(df['sepal_length']>5) | (df['sepal_width']==3)]   # | means any one condition should be satisfy

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
10            5.4          3.7           1.5          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[124 rows x 5 columns]

# groups

In [55]:
df.groupby(["sepal_length"]) ['petal_length'].mean()    #groups the data with sepal length WRT petal length avg

sepal_length
4.3    1.100000
4.4    1.333333
4.5    1.300000
4.6    1.325000
4.7    1.450000
4.8    1.580000
4.9    2.266667
5.0    1.840000
5.1    1.722222
5.2    2.075000
5.3    1.500000
5.4    2.033333
5.5    3.228571
5.6    4.200000
5.7    3.587500
5.8    4.071429
5.9    4.700000
6.0    4.650000
6.1    4.750000
6.2    4.750000
6.3    5.133333
6.4    5.157143
6.5    5.240000
6.6    4.500000
6.7    5.262500
6.8    5.400000
6.9    5.275000
7.0    4.700000
7.1    5.900000
7.2    5.966667
7.3    6.300000
7.4    6.100000
7.6    6.600000
7.7    6.600000
7.9    6.400000
Name: petal_length, dtype: float64

In [56]:
df.groupby(["sepal_width"]) ['petal_width'].var()

sepal_width
2.0         NaN
2.2    0.083333
2.3    0.222500
2.4    0.003333
2.5    0.125714
2.6    0.262000
2.7    0.117778
2.8    0.156099
2.9    0.195111
3.0    0.553985
3.1    0.822727
3.2    0.839231
3.3    1.006667
3.4    0.736061
3.5    0.024000
3.6    1.363333
3.7    0.013333
3.8    0.872000
3.9    0.000000
4.0         NaN
4.1         NaN
4.2         NaN
4.4         NaN
Name: petal_width, dtype: float64

In [57]:
df.groupby(["sepal_width",'sepal_width']) ['petal_width'].describe()

count      mean       std  min    25%   50%    75%  \
sepal_width sepal_width                                                       
2.0         2.0            1.0  1.000000       NaN  1.0  1.000  1.00  1.000   
2.2         2.2            3.0  1.333333  0.288675  1.0  1.250  1.50  1.500   
2.3         2.3            4.0  0.975000  0.471699  0.3  0.825  1.15  1.300   
2.4         2.4            3.0  1.033333  0.057735  1.0  1.000  1.00  1.050   
2.5         2.5            8.0  1.550000  0.354562  1.1  1.250  1.60  1.825   
2.6         2.6            5.0  1.420000  0.511859  1.0  1.200  1.20  1.400   
2.7         2.7            9.0  1.555556  0.343188  1.0  1.300  1.60  1.900   
2.8         2.8           14.0  1.707143  0.395094  1.2  1.325  1.65  2.000   
2.9         2.9           10.0  1.320000  0.441714  0.2  1.300  1.30  1.475   
3.0         3.0           26.0  1.403846  0.744301  0.1  1.225  1.55  1.950   
3.1         3.1           11.0  1.245455  0.907043  0.1  0.200  1.50  1.950   
3.2         3.2           13.0  1.261538  0.916095  0.2  0.200  1.50  2.000   
3.3         3.3            6.0  1.566667  1.003328  0.2  0.775  1.85  2.400   
3.4         3.4           12.0  0.716667  0.857940  0.2  0.200  0.25  0.700   
3.5         3.5            6.0  0.300000  0.154919  0.2  0.200  0.25  0.300   
3.6         3.6            4.0  0.750000  1.167619  0.1  0.175  0.20  0.775   
3.7         3.7            3.0  0.266667  0.115470  0.2  0.200  0.20  0.300   
3.8         3.8            6.0  0.900000  0.933809  0.2  0.300  0.35  1.600   
3.9         3.9            2.0  0.400000  0.000000  0.4  0.400  0.40  0.400   
4.0         4.0            1.0  0.200000       NaN  0.2  0.200  0.20  0.200   
4.1         4.1            1.0  0.100000       NaN  0.1  0.100  0.10  0.100   
4.2         4.2            1.0  0.200000       NaN  0.2  0.200  0.20  0.200   
4.4         4.4            1.0  0.400000       NaN  0.4  0.400  0.40  0.400   

                         max  
sepal_width sepal_width       
2.0         2.0          1.0  
2.2         2.2          1.5  
2.3         2.3          1.3  
2.4         2.4          1.1  
2.5         2.5          2.0  
2.6         2.6          2.3  
2.7         2.7          1.9  
2.8         2.8          2.4  
2.9         2.9          1.8  
3.0         3.0          2.3  
3.1         3.1          2.4  
3.2         3.2          2.3  
3.3         3.3          2.5  
3.4         3.4          2.4  
3.5         3.5          0.6  
3.6         3.6          2.5  
3.7         3.7          0.4  
3.8         3.8          2.2  
3.9         3.9          0.4  
4.0         4.0          0.2  
4.1         4.1          0.1  
4.2         4.2          0.2  
4.4         4.4          0.4

# Add & Del a column

In [58]:
#add a new column        #to all customized colum
df["new_col"]=1
l=[]
for i in df["sepal_length"]:
    if i%2==0:
        l.append("even")
    else:
        l.append("odd")
df["new_col"]=l
df

sepal_length  sepal_width  petal_length  petal_width    species new_col
0             5.1          3.5           1.4          0.2     setosa     odd
1             4.9          3.0           1.4          0.2     setosa     odd
2             4.7          3.2           1.3          0.2     setosa     odd
3             4.6          3.1           1.5          0.2     setosa     odd
4             5.0          3.6           1.4          0.2     setosa     odd
..            ...          ...           ...          ...        ...     ...
145           6.7          3.0           5.2          2.3  virginica     odd
146           6.3          2.5           5.0          1.9  virginica     odd
147           6.5          3.0           5.2          2.0  virginica     odd
148           6.2          3.4           5.4          2.3  virginica     odd
149           5.9          3.0           5.1          1.8  virginica     odd

[150 rows x 6 columns]

In [59]:
df.drop(["new_col"],axis=1,inplace=True)    #to del axis=1 for column and axis=0 for row 
                                            #inplace=true will save and false will show but not save

# Sorting of data

In [60]:
df.sort_values(['sepal_length'],ascending=[False])

sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
..            ...          ...           ...          ...        ...
41            4.5          2.3           1.3          0.3     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
13            4.3          3.0           1.1          0.1     setosa

[150 rows x 5 columns]

In [61]:
df.sort_values(['sepal_length','petal_length'],ascending=[False,True])

sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
..            ...          ...           ...          ...        ...
41            4.5          2.3           1.3          0.3     setosa
38            4.4          3.0           1.3          0.2     setosa
42            4.4          3.2           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
13            4.3          3.0           1.1          0.1     setosa

[150 rows x 5 columns]

# Num_Py

In [62]:
import numpy as np
#pip install numpy
#!pip install numpy
#conda install numpy

In [63]:
l=[[1,2],
   [2,3]]  #this is list not a matrix

In [64]:
type(l)

list

In [65]:
l+l   #concat 

[[1, 2], [2, 3], [1, 2], [2, 3]]

In [66]:
a=np.array(l)                #converting to matrix
b=np.array([[4,5],[7,8]])

In [67]:
type(a)  #shows type

numpy.ndarray

In [68]:
a.shape #shows matrix 

(2, 2)

In [69]:
a+b #add

array([[ 5,  7],
       [ 9, 11]])

In [70]:
a*2 #multiply by 2 to each number

array([[2, 4],
       [4, 6]])

In [71]:
a**2 #square

array([[1, 4],
       [4, 9]], dtype=int32)

In [72]:
b.T #transpose

array([[4, 7],
       [5, 8]])

In [73]:
a*b  #multiply element to element

array([[ 4, 10],
       [14, 24]])

In [74]:
a

array([[1, 2],
       [2, 3]])

In [75]:
np.dot(a,b) #matrix multiplication

array([[18, 21],
       [29, 34]])

In [76]:
np.matmul(a,b) #matrix multiplication

array([[18, 21],
       [29, 34]])

In [78]:
a

array([[1, 2],
       [2, 3]])

In [81]:
b=np.linalg.inv(a)  #inverse matrix
b

array([[-3.,  2.],
       [ 2., -1.]])

In [82]:
np.dot(a,b)  #identity matrix for inverse

array([[1., 0.],
       [0., 1.]])

In [83]:
np.sin(1)

0.8414709848078965

In [84]:
np.cos(1)

0.5403023058681398

In [85]:
np.exp(1)

2.718281828459045

In [86]:
np.log(10)

2.302585092994046

In [87]:
a

array([[1, 2],
       [2, 3]])

In [89]:
a[::-1,:] #reverse of row

array([[2, 3],
       [1, 2]])

In [90]:
a[::-1,::-1]   #reverse of row & col

array([[3, 2],
       [2, 1]])

In [91]:
np.mean(a,axis=0)

array([1.5, 2.5])

In [92]:
np.mean(a,axis=1)

array([1.5, 2.5])

In [93]:
b

array([[-3.,  2.],
       [ 2., -1.]])

In [94]:
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [95]:
np.mean(b,axis=0)     #axis=0 down by down

array([2., 3.])

In [96]:
np.mean(b,axis=1)    #axis=1 side by side

array([1.5, 3.5])

In [97]:
np.mean(b)

2.5

In [98]:
np.median(b)

2.5

In [99]:
np.median(b,axis=0)

array([2., 3.])

In [100]:
np.concatenate([a,a])

array([[1, 2],
       [2, 3],
       [1, 2],
       [2, 3]])

In [101]:
np.concatenate([a,a],axis=1)

array([[1, 2, 1, 2],
       [2, 3, 2, 3]])