In [86]:
import pandas as pd
import numpy as np

In [87]:
import warnings
warnings.filterwarnings("ignore")

In [89]:
glaxo_df = pd.read_csv("glaxo_df.csv")
glaxo_df.head()

Date      Date.1    Close      gain
0  2010-01-05  2010-01-05  1616.80 -0.005444
1  2010-01-06  2010-01-06  1638.50  0.013422
2  2010-01-07  2010-01-07  1648.70  0.006225
3  2010-01-08  2010-01-08  1639.80 -0.005398
4  2010-01-11  2010-01-11  1629.45 -0.006312

In [90]:
glaxo_df_ci = stats.norm.interval(0.95,
glaxo_df.gain.mean(),
glaxo_df.gain.std())
print( 'Gain at 95% confidence interval is:', np.round(glaxo_df_ci,3))

Gain at 95% confidence interval is: [-0.026  0.027]


In [91]:
beml_df=pd.read_csv('beml_df.csv')
beml_df_ci = stats. norm.interval(0.95,
beml_df.gain.mean(),
beml_df.gain.std())
np.round(beml_df_ci,3)

array([-0.052,  0.052])

# T-distribution

In [92]:
beml_df=pd.read_csv('beml_df.csv')

beml_df_ci = stats. t .interval(0.95,1737,
beml_df.gain.mean(),
beml_df.gain.std())
np.round(beml_df_ci,3)

array([-0.052,  0.052])

In [93]:
glaxo_df=pd.read_csv('glaxo_df.csv')

glaxo_df_ci = stats.t.interval(0.95,1737,
glaxo_df.gain.mean(),
glaxo_df.gain.std())
np.round(glaxo_df_ci, 3)

array([-0.026,  0.027])